using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Iadeptmain.Classes
{
    public partial class CValues
    {
        public const string SCNSTAX = "A_X";
        public const string SCNSTAXl = "Axial";
        public const string SCNSTAY = "A_Y";
        public const string SCNSTCBOX = "CheckBox";
        public const string SCNSTDDA = "Data_Demodulate_A";
        public const string SCNSTDDH = "Data_Demodulate_H";
        public const string SCNSTDDV = "Data_Demodulate_V";
        public const string SCNSTDPH = "Data_Power_H";
        public const string SCNSTDPV = "Data_Power_V";
        public const string SCNSTDT = "DateTime";
        public const string SCNSTDTH = "Data_TimeH";
        public const string SCNSTDTPA = "Data_Power_A";
        public const string SCNSTDTTA = "Data_TimeA";
        public const string SCNSTDTV = "Data_TimeV";
        public const string SCNSTFDML = "Demodulate";
        public const string SCNSTFPW = "Power";
        public const string SCNSTFTM = "Time";
        public const string SCNSTHRZ = "Horizontal";
        public const string SCNSTHX = "H_X";
        public const string SCNSTHY = "H_Y";
        public const string SCNSTLM = "LayoutManager";
        public const string SCNSTM = "M";
        public const string SCNSTMAC = "Machine";
        public const string SCNSTMTRID = "MachineTrainID";
        public const string SCNSTNPS = "NodePosition";
        public const string SCNSTOLP = "Overlap";
        public const string SCNSTPNTMACID = "PointMachineID";
        public const string SCNSTPPOS = "PointPosition";
        public const string SCNSTQDML = "select * from Data_Demodulate where Point_ID='";
        public const string SCNSTQDP = "select * from Data_Power where Point_ID='";
        public const string SCNSTQDT = "select * from Point_data where Point_ID='";
        public const string SCNSTQDT23 = "select fac.Name as factoryname,mac.Name as machinename,pd.accel_a as overall from Point_data pd inner join point pt on pt.point_id= pd.Point_ID left join machine_info mac on mac.Machine_ID=pt.Machine_ID left join train_info tra on tra.Train_ID=mac.TrainID left join area_info ar on ar.Area_ID=tra.Area_ID left join factory_info fac on fac.Factory_ID=ar.FactoryID where ";
        public const string SCNSTQDT24 = "select fac.Name as factoryname,mac.Name as machinename,pd.vel_a as overall from Point_data pd inner join point pt on pt.point_id= pd.Point_ID left join machine_info mac on mac.Machine_ID=pt.Machine_ID left join train_info tra on tra.Train_ID=mac.TrainID left join area_info ar on ar.Area_ID=tra.Area_ID left join factory_info fac on fac.Factory_ID=ar.FactoryID where ";
        public const string SCNSTQDT25 = "select fac.Name as factoryname,mac.Name as machinename,pd.displ_a as overall from Point_data pd inner join point pt on pt.point_id= pd.Point_ID left join machine_info mac on mac.Machine_ID=pt.Machine_ID left join train_info tra on tra.Train_ID=mac.TrainID left join area_info ar on ar.Area_ID=tra.Area_ID left join factory_info fac on fac.Factory_ID=ar.FactoryID where ";
        public const string SCNSTQDT26 = "select fac.Name as factoryname,mac.Name as machinename,pd.bearing_a as overall from Point_data pd inner join point pt on pt.point_id= pd.Point_ID left join machine_info mac on mac.Machine_ID=pt.Machine_ID left join train_info tra on tra.Train_ID=mac.TrainID left join area_info ar on ar.Area_ID=tra.Area_ID left join factory_info fac on fac.Factory_ID=ar.FactoryID where ";
        public const string SCNSTQORDUID = "' order by UID asc";
        public const string SCNSTSLSPLIT = "|";
        public const string SCNSTT = "T";
        public const string SCNSTTAID = "TrainAreaID";
        public const string SCNSTTRN = "Train";
        public const string SCNSTVER = "Vertical";
        public const string SCNSTVX = "V_X";
        public const string SCNSTVY = "V_Y";
        public const string SCNSTXUSCVAL = "X_Value";
        public const string SCNSTYUSCVAL = "Y_Value";
        public const string SCONSTA = "A";
        public const string SCONSTAPID = "AreaPlantID";
        public const string SCONSTAPLNTXS = "//FactoryManager/Plants";
        public const string SCONSTAR = "Area";
        public const string SCONSTATNAME = "'][@name='";
        public const string SCONSTATRTBFF = @"\Benstone\FactoryManager.xml";
        public const string SCONSTBEST = "Benstone";
        public const char SCONSTBLK = ' ';
        public const string SCONSTBST = @"\Benstone\";
        public const string SCONSTCB = "";
        public const string SCONSTCC = "Check Connections";
        public const string SCONSTCHBG = "CheckHaspBG";
        public const string SCONSTCN = "Check Name";
        public const string SCONSTDBF = ".sdf";
        public const string SCONSTDC = "Status:Device Connected";
        public const string SCONSTDCD = @"\DataCollector\Data\";
        public const string SCONSTDDBCS = "server=localhost;uid=root;database=DemoDataBase";
        public const string SCONSTDEV = "Device";
        public const string SCONSTDI = "ID";
        public const string SCONSTDNC = "Status:Device Not Connected";
        public const string SCONSTELM = "Element";
        public const string SCONSTEXP = "Expand Nodes";
        public const string SCONSTFCS = "server=localhost;database=mysql;uid=root";
        public const string SCONSTFCT = "Factory";
        public const string SCONSTFDB = "DemoDataBase";
        public const string SCONSTFMPLTSPLT = "/FactoryManager/Plants/Plant[@name='";
        public const string SCONSTFNAME = "Microsoft Sans Serif";
        public const string SCONSTFP = "FIELDPAQ";
        public const string SCONSTFPOS = "FactoryPosition";
        public const string SCONSTFRMOTHTH = "FromOtherThread";
        public const string SCONSTIBST = "Impaq-Benstone";
        public const string SCONSTIDIP = "'][@ID='";
        public const string SCONSTIM = "IMPAQ";
        public const string SCONSTLBRC = "']";
        public const string SCONSTLC = "Status:Loading Completed";
        public const string SCONSTMACINTRN = "//FactoryManager/Plants/Plant/Area/Train/Machine[@ID='";
        public const string SCONSTMSFCSS = "File Copied to Instrument Successfully";
        public const string SCONSTMY = @"\MySqlWI\mysql-5.0.51b-win32\bin\mysqld.exe";
        public const string SCONSTMYSQLW32 = @"\mysql-5.0.51b-win32";
        public const string SCONSTMYSQLWI = "MySqlWI";
        public const string SCONSTNM = "name";
        public const string SCONSTNNV = "Name Not Valid";
        public const string SCONSTOTHDI = "DI-460";
        public const string SCONSTOTHINST = "DI-460";
        public const string SCONSTP = "P";
        public const string SCONSTPLTINAR = "//FactoryManager/Plants/Plant/Area[@ID='";
        public const string SCONSTPNT = "Point";
        public const string SCONSTPSN = "Position";
        public const string SCONSTPTACTDA = "Please try again.Connect the device again";
        public const string SCONSTPTINMAC = "//FactoryManager/Plants/Plant/Area/Train/Machine/Point[@ID='";
        public const string SCONSTPWDN = "Device Not Present!.Please check the connections.";
        public const string SCONSTPWWC = "Status:Please wait while copying";
        public const string SCONSTPWWIDB = "Status:Please Wait!.Initializing DataBase";
        public const string SCONSTRES = "Resource";
        public const string SCONSTSBLK = " ";
        public const string SCONSTSCDB = ";database=";
        public const string SCONSTSDBIC = "Status:DB Initialization Completed";
        public const string SCONSTSE = "SubElement";
        public const string SCONSTSIC = "Status:DB Initialization Completed";
        public const string SCONSTSLP = "SimpleLinePlot";
        public const string SCONSTSTCOP = "Status:Copying";
        public const string SCONSTSTFCSS = "Status:File Copied Successfully";
        public const string SCONSTSTLOD = "Status:Loading";
        public const string SCONSTTRNINAR = "//FactoryManager/Plants/Plant/Area/Train[@ID='";
        public const string SCONSTUPLD = "UpLoad";
        public const string SCONSTXVAL = "X Value:";
        public const string SCONSTXY = @"X Value:0 
 Y Value:0";
        public const string SCONSTYVAL = "Y Value:";
        public const string SCONTSCBXCTRL = "CheckBoxControl";
        public const string SCONTSOND = "Second";

        public static byte[] SCONSTEIGHT;
        public static byte[] SCONSTFIVE;
        public static byte[] SCONSTFOUR;
        public static byte[] SCONSTNINE;
        public static byte[] SCONSTONE;
        public static byte[] SCONSTSEVEN;
        public static byte[] SCONSTSIX;
        public static byte[] SCONSTTEN;
        public static byte[] SCONSTTHREE;
        public static byte[] SCONSTTWO;
    }
}

